package com.cxk.fuckxixi.user;

/*
 *Generated by IDE
 */


public class UserProfileUnit {

    private static String username;

    private static String password;

    private static String nick;

    private static String school;

    private static String classname;

    private static String worksJson;

    private static String token;




    //其它

    public static String getToken() {return token;}

    public static void setToken(String token) {
        UserProfileUnit.token = token;}

    public static String getUsername() {
        return username;
    }

    public static void setUsername(String username) {
        UserProfileUnit.username = username;
    }

    public static String getPassword() {
        return password;
    }

    public static void setPassword(String password) {
        UserProfileUnit.password = password;
    }

    public static String getNick() {
        return nick;
    }

    public static void setNick(String nick) {
        UserProfileUnit.nick = nick;
    }

    public static String getSchool() {
        return school;
    }

    public static void setSchool(String school) {
        UserProfileUnit.school = school;
    }

    public static String getClassname() {
        return classname;
    }

    public static void setClassname(String classname) {
        UserProfileUnit.classname = classname;
    }

    public static String getWorksJson() {
        return worksJson;
    }

    public static void setWorksJson(String worksJson) {
        UserProfileUnit.worksJson = worksJson;
    }



}
